name: Create Azure Document Intelligence Resource with Role Assignment

trigger: none

parameters:
- name: location
  type: string
  default: "eastus"
- name: RESOURCE_GROUP
  type: string
  default: "projArthurreis"
- name: documentIntelligenceName
  displayName: 'Azure Document Intelligence Resource Name'
  type: string
- name: sku
  displayName: 'Azure Document Intelligence SKU'
  type: string
  default: 'S0'
- name: role
  displayName: 'Role to Assign'
  type: string
  default: 'Cognitive Services User'
- name: principalId
  displayName: 'Principal ID (Object ID) for Role Assignment'
  type: string

variables:
- group: Arthur_VG

stages:
- stage: CheckResources
  displayName: 'Check Resource Group Stage'
  jobs:
  - job: CheckResourceGroup
    displayName: 'Check or Create Resource Group'
    steps:
    - task: AzureCLI@2
      displayName: 'Check or Create Resource Group'
      inputs:
        azureSubscription: $(service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >-
          echo "Checking if resource group '${{ parameters.RESOURCE_GROUP }}' exists..."

          exists=$(az group exists --name ${{ parameters.RESOURCE_GROUP }})

          echo "az returned: $exists"

          if [ "$exists" = "false" ]; then
            echo "##[warning] Resource group does not exist. Creating it now..."
            az group create --name ${{ parameters.RESOURCE_GROUP }} --location ${{ parameters.location }} --only-show-errors
            echo "✅ Resource group created successfully."
          else
            echo "✅ Resource group exists."
          fi

- stage: ValidateDocumentIntelligence
  displayName: 'Validate Azure Document Intelligence Configuration'
  jobs:
  - job: ValidateDocumentIntelligenceName
    displayName: 'Validate Azure Document Intelligence Name'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Validate Azure Document Intelligence Name Format'
      inputs:
        azureSubscription: $(service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          if [[ ! "${{ parameters.documentIntelligenceName }}" =~ ^[a-zA-Z0-9-]{2,64}$ ]]; then
            echo "##[error] Azure Document Intelligence name must be 2-64 alphanumeric characters and hyphens"
            exit 1
          fi
          echo "✅ Azure Document Intelligence name validation passed"

- stage: CreateDocumentIntelligence
  displayName: 'Create Azure Document Intelligence Resource'
  jobs:
  - job: CreateDocumentIntelligenceJob
    displayName: 'Create Azure Document Intelligence'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Create Azure Document Intelligence Resource'
      inputs:
        azureSubscription: $(service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          echo "Creating Azure Document Intelligence resource: ${{ parameters.documentIntelligenceName }}"

          az cognitiveservices account create \
            --name "${{ parameters.documentIntelligenceName }}" \
            --resource-group "${{ parameters.RESOURCE_GROUP }}" \
            --location "${{ parameters.location }}" \
            --kind FormRecognizer \
            --sku "${{ parameters.sku }}" \
            --yes \
            --output table
          
          echo "✅ Azure Document Intelligence resource created successfully"

- stage: WaitForProvisioning
  displayName: 'Wait for Azure Document Intelligence Provisioning'
  jobs:
  - job: WaitJob
    displayName: 'Wait 30 seconds'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      displayName: 'Sleep for 30 seconds'
      inputs:
        targetType: 'inline'
        script: |
          echo "Waiting 30 seconds for Azure Document Intelligence resource to be fully provisioned..."
          sleep 30
          echo "✅ Wait completed"

- stage: AssignRole
  displayName: 'Assign Role to Principal'
  jobs:
  - job: AssignRoleJob
    displayName: 'Assign Role to Azure Document Intelligence'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Assign Role to Principal'
      inputs:
        azureSubscription: $(service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: >
          echo "Assigning role '${{ parameters.role }}' to principal '${{ parameters.principalId }}'"

          DI_RESOURCE_ID=$(az cognitiveservices account show \
            --name "${{ parameters.documentIntelligenceName }}" \
            --resource-group "${{ parameters.RESOURCE_GROUP }}" \
            --query id -o tsv)
          
          az role assignment create \
            --assignee "${{ parameters.principalId }}" \
            --role "${{ parameters.role }}" \
            --scope "$DI_RESOURCE_ID" \
            --output table
          
          echo "✅ Role assignment completed successfully"

- stage: SmokeTest
  displayName: 'Smoke Test Azure Document Intelligence Resource'
  jobs:
  - job: SmokeTestJob
    displayName: 'Verify Azure Document Intelligence Exists'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Check Azure Document Intelligence Exists'
      inputs:
        azureSubscription: $(service_conn)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Verifying Azure Document Intelligence resource '${{ parameters.documentIntelligenceName }}' exists..."

          if az cognitiveservices account show --name "${{ parameters.documentIntelligenceName }}" --resource-group "${{ parameters.RESOURCE_GROUP }}" &> /dev/null; then
            echo "✅ Azure Document Intelligence Resource '${{ parameters.documentIntelligenceName }}' exists."
            
            echo "========================================"
            echo "Azure Document Intelligence Resource Details:"
            echo "========================================"
            az cognitiveservices account show \
              --name "${{ parameters.documentIntelligenceName }}" \
              --resource-group "${{ parameters.RESOURCE_GROUP }}" \
              --output table
            
            echo ""
            echo "Azure Document Intelligence Configuration:"
            echo "- Name: ${{ parameters.documentIntelligenceName }}"
            echo "- Resource Group: ${{ parameters.RESOURCE_GROUP }}"
            echo "- Location: ${{ parameters.location }}"
            echo "- SKU: ${{ parameters.sku }}"
            echo "- Role Assigned: ${{ parameters.role }}"
            echo "- Principal ID: ${{ parameters.principalId }}"
            
            echo "========================================"
          else
            echo "❌ ##[error] ERROR: Azure Document Intelligence Resource '${{ parameters.documentIntelligenceName }}' does not exist in resource group ${{ parameters.RESOURCE_GROUP }} or an error occurred." >&2
            exit 1
          fi

          echo "✅ Smoke test completed successfully."
